version: '3.9'

services:
  proxy:
    image: caddy:2
    ports: 
      - "80:80"
      - "443:443"
      - "3080:3080"  # Direct LibreChat access for development
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - librechat
    profiles:
      - proxy

  librechat:
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - MONGO_URI=${MONGODB_URI:-mongodb://mongodb:27017/voygent}
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-meilisearch_master_key}
    volumes:
      - ./config/librechat.yaml:/app/librechat.yaml:ro
      - ./data/uploads:/app/client/public/images/uploads
      - ./data/logs:/app/logs
    depends_on:
      - mongodb
      - meilisearch
    ports:
      - "3080:3080"  # Direct access for development

  # Orchestrator service - only runs in local/hybrid database mode
  orchestrator:
    build: 
      context: ./orchestrator
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
      - ./db:/app/db
    ports:
      - "3000:3000"  # Direct access for development
    profiles:
      - local-database
      - hybrid
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-voygent}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-voygent123}
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-voygent}
    volumes:
      - ./data/mongodb:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - "27017:27017"  # Direct access for development

  meilisearch:
    image: getmeili/meilisearch:v1.5
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-meilisearch_master_key}
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./data/meilisearch:/meili_data
    ports:
      - "7700:7700"  # Direct access for development

volumes:
  caddy_data:
  caddy_config: