# VoygentCE LibreChat Configuration
# This configuration integrates MCP servers for travel planning functionality

version: 1.1.0
cache: true

endpoints:
  custom:
    - name: "Anthropic"
      apiKey: "${ANTHROPIC_API_KEY}"
      baseURL: "https://api.anthropic.com/v1"
      models:
        default: ["claude-3-5-sonnet-20241022", "claude-3-5-haiku-20241022"]
        fetch: false
      titleConvo: true
      titleMethod: "completion"
      titleModel: "claude-3-5-haiku-20241022"
      # MCP Servers integrated with this endpoint
      mcpServers:
{{#if_chrome_exists}}
        chrome:
          command: "node"
          args: ["${MCP_CHROME_PATH}"]
          description: "Browser automation for hotel booking sites"
{{/if_chrome_exists}}
{{#if_database_local}}
        orchestrator:
          baseUrl: "http://orchestrator:3000/api"
          description: "Local trip and hotel data management"
          serverInstructions: |
            This MCP server provides trip planning capabilities via local orchestrator.
            Running in LOCAL MODE - data stored locally with full privacy.
            Use city planning to get Low/Medium/High recommendations for clients.
          tools:
            - create_trip
            - ingest_hotels
            - ingest_rooms
            - refresh_facts
            - query_facts
            - plan_city
            - render_proposal
{{/if_database_local}}
{{#if_database_remote}}
        d1_database:
          transport:
            type: "sse"
            url: "${MCP_D1_DATABASE_SSE_URL}"
          description: "Advanced trip and hotel data management (Remote Mode)"
          serverInstructions: |
            This MCP server provides advanced trip planning capabilities via Cloudflare Workers.
            Running in REMOTE MODE - data stored in Cloudflare D1 with advanced features.
            
            Available tools include:
            - get_anything: Comprehensive search across all trip data
            - create_trip_with_client: Create trips with client assignment
            - bulk_trip_operations: Multi-operation transactions
            
            Prefer get_anything for broad searches and specific tools for targeted operations.
{{/if_database_remote}}
{{#if_instructions_remote}}
        prompt_instructions:
          transport:
            type: "sse"
            url: "${MCP_PROMPT_INSTRUCTIONS_SSE_URL}"
          description: "Workflow and conversation management (Remote Mode)"
          serverInstructions: |
            This MCP server manages travel agent workflows and conversation state.
            Running in REMOTE MODE - provides advanced workflow coordination.
            
            Key capabilities:
            - travel_agent_start: Initialize travel planning workflows
            - continue_trip: Resume work on existing trips with full context
            - get_instruction: Retrieve workflow-specific guidance
{{/if_instructions_remote}}
    - name: "OpenAI"
      apiKey: "${OPENAI_API_KEY}"
      baseURL: "https://api.openai.com/v1"
      models:
        default: ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-3.5-turbo"]
        fetch: false
      titleConvo: true
      titleMethod: "completion"
      titleModel: "gpt-4o-mini"
      # MCP Servers can also be added to OpenAI endpoint if needed
      mcpServers:
{{#if_chrome_exists}}
        chrome:
          command: "node"
          args: ["${MCP_CHROME_PATH}"]
          description: "Browser automation for hotel booking sites"
{{/if_chrome_exists}}
{{#if_database_remote}}
        d1_database:
          transport:
            type: "sse"
            url: "${MCP_D1_DATABASE_SSE_URL}"
          description: "Advanced trip and hotel data management"
{{/if_database_remote}}
{{#if_instructions_remote}}
        prompt_instructions:
          transport:
            type: "sse"
            url: "${MCP_PROMPT_INSTRUCTIONS_SSE_URL}"
          description: "Workflow and conversation management"
{{/if_instructions_remote}}

# Interface configuration
interface:
  privacyPolicy:
    externalUrl: "https://voygent.app/privacy"
  termsOfService:
    externalUrl: "https://voygent.app/terms"

# File handling
fileConfig:
  endpoints:
    custom:
      fileLimit: 20
      fileSizeLimit: 10  # MB
      totalSizeLimit: 50  # MB
      supportedMimeTypes:
        - "image/jpeg"
        - "image/png"
        - "image/webp"
        - "image/gif"
        - "text/plain"
        - "application/pdf"

# Registration
registration:
  socialLogins: ["discord", "facebook", "github", "google", "openid"]
  
# Rate limiting  
rateLimits:
  fileUploads:
    ipMax: 100
    ipWindowInMinutes: 60
    userMax: 50
    userWindowInMinutes: 60